[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "aegis-game"
description = "Survivor Simulation Game"
version = "2.9.10"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
 "numpy>=2.5.2",
 "packaging>=26.3",
 "protobuf>=7.36.1",
 "pyyaml>=6.0.3",
 "requests>=2.34.2",
 "restrictedpython>=8.5",
 "websocket-server==0.6.4",
]

[dependency-groups]
dev = [ 
    "gitpython>=3.1.61", 
    "griffe>=2.2.0", 
    "hatch>=1.18.0", 
    "pytest>=9.1.1", 
    "ruff>=0.16.5", 
    "semver>=3.0.4", 
    "toml>=0.10.2",
]

[project.urls]
Documentation = "https://aegis-game.github.io/aegis-docs/"
Repository = "https://github.com/AEGIS-GAME/aegis"

[project.scripts]
aegis = "aegis_game:main"

[tool.ruff]
line-length = 88
exclude = [ "src/_aegis_game/sandbox.py", "src/_aegis_game/schemas/**", "agents/**", "src/_aegis_game/templates/**",]

[tool.pyright]
ignore = [ "reportMissingTypeStubs",]

[tool.ruff.lint]
select = [ "ALL",]
ignore = [ "S311", "D203", "D212", "COM812", "FIX002", "ERA001", "E501", "TD002", "TD003", "T201", "S101", "CPY001",]

[tool.hatch.build.targets.wheel]
packages = [ "src/aegis_game", "src/_aegis_game",]
include = [ "src/_aegis_game/templates/**/*",]
