name: Aegis CI

on:
  push:
    branches: [main]

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.8.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: 20 
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: bump
        working-directory: client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
